services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest-ubi8
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  servicio-usuarios:
    build: ./servicio-usuarios
    ports:
      - "3001:3001"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

  servicio-notificaciones:
    build: ./servicio-notificaciones
    ports:
      - "3002:3002"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
